### PR TITLE
List of companies structured by business type

### PR DESCRIPTION
**Pull request by drolbr**
Dear Mikel,

Thank you for setting up the Welcome Mat.

I suggest the following reordering of the companies list into categories. The rationale is to let the list look less arbitrary.

Best regards,
Roland

### CODE REVIEW

**Comment by mikelmaron** [comment]
Thanks for looking at this @drolbr. Can you explain what "Forbes" and "Platform" are supposed to mean here?

**Comment by drolbr** [comment]
Thank you for asking back.

The "Forbes" label is intended to refer to the Forbes List of Big Companies. Two alternatives are to list by market capitalization or by total revenue, or to simply talk about "very big" companies.

I thought the Forbes list is both well-known or generally acclaimed. Apparently it is not, thus we should change to a different proxy for "very big".

The "platform" category is intended to collect all the companies that are based on user generated content. In particular, there needs to be a proper place for the Wikimedia foundation. "Telenav" is misplaced and should better go to "Geodata Software and Service"; I'm sorry for the oversight.

That said, I am very open for other categories. The idea is to make the choice of names more transparent, not these particular categories.

**Comment by mikelmaron** [comment]
@drolbr Yes figured that's what you meant by Forbes, but you're right, it's not universally understood. I think "Very large companies" is accurate, but a little strange. Maybe "Major platforms" or "Major sites" and include Wikipedia in that list? Then for "Digital Matchmakers", perhaps more appropriate to say "Social sites"? And perhaps move Uber and Grab under the "Transportation" heading?

**Comment by drolbr** [comment]
Thank you for the feedback. I just have included the suggested changes.

**Comment by mikelmaron** [comment]
Thanks @drolbr, merging

**Pull request merged**
